
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Windows - 10.0.26200 - AMD64
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CheckCCompilerFlag.cmake:51 (cmake_check_compiler_flag)"
      - "build/external/raylib-master/cmake/AddIfFlagCompiles.cmake:3 (CHECK_C_COMPILER_FLAG)"
      - "build/external/raylib-master/cmake/CompilerFlags.cmake:5 (add_if_flag_compiles)"
      - "build/external/raylib-master/CMakeLists.txt:34 (include)"
    checks:
      - "Performing Test COMPILER_HAS_THOSE_TOGGLES"
    directories:
      source: "D:/yxu/mesh3d/build/web/CMakeFiles/CMakeScratch/TryCompile-ylwwvd"
      binary: "D:/yxu/mesh3d/build/web/CMakeFiles/CMakeScratch/TryCompile-ylwwvd"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "D:/emsdk/upstream/emscripten/emscan-deps.bat"
      CMAKE_C_FLAGS: ""
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "D:/emsdk/upstream/emscripten/cmake/Modules;D:/emsdk/upstream/emscripten/cmake/Modules;D:/emsdk/upstream/emscripten/cmake/Modules;D:/emsdk/upstream/emscripten/cmake/Modules;D:/emsdk/upstream/emscripten/cmake/Modules;D:/yxu/mesh3d/build/external/raylib-master/cmake"
    buildResult:
      variable: "COMPILER_HAS_THOSE_TOGGLES"
      cached: true
      stdout: |
        Change Dir: 'D:/yxu/mesh3d/build/web/CMakeFiles/CMakeScratch/TryCompile-ylwwvd'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/msys64/ucrt64/bin/mingw32-make.exe -f Makefile cmTC_f65ad/fast
        C:/msys64/ucrt64/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_f65ad.dir\\build.make CMakeFiles/cmTC_f65ad.dir/build
        mingw32-make[1]: Entering directory 'D:/yxu/mesh3d/build/web/CMakeFiles/CMakeScratch/TryCompile-ylwwvd'
        Building C object CMakeFiles/cmTC_f65ad.dir/src.c.o
        D:\\emsdk\\upstream\\emscripten\\emcc.bat -DCOMPILER_HAS_THOSE_TOGGLES  -Werror=pointer-arith -MD -MT CMakeFiles/cmTC_f65ad.dir/src.c.o -MF CMakeFiles\\cmTC_f65ad.dir\\src.c.o.d -o CMakeFiles\\cmTC_f65ad.dir\\src.c.o -c D:\\yxu\\mesh3d\\build\\web\\CMakeFiles\\CMakeScratch\\TryCompile-ylwwvd\\src.c
        Linking C executable cmTC_f65ad.js
        "C:\\Program Files\\CMake\\bin\\cmake.exe" -E cmake_link_script CMakeFiles\\cmTC_f65ad.dir\\link.txt --verbose=1
        D:\\emsdk\\upstream\\emscripten\\emcc.bat @CMakeFiles\\cmTC_f65ad.dir\\objects1.rsp -o cmTC_f65ad.js
        mingw32-make[1]: Leaving directory 'D:/yxu/mesh3d/build/web/CMakeFiles/CMakeScratch/TryCompile-ylwwvd'
        
      exitCode: 0
...
